// MIT License

// WARNING: This file has automatically been generated on Tue, 17 Feb 2026 22:14:16 MSK.
// Code generated by https://git.io/c-for-go. DO NOT EDIT.

#include "../../internal/SPIRV-Reflect/spirv_reflect.h"
#include <stdlib.h>
#pragma once

#define __CGOGEN 1

