// MIT License

// WARNING: This file has automatically been generated on Thu, 19 Feb 2026 22:41:19 MSK.
// Code generated by https://git.io/c-for-go. DO NOT EDIT.

/*
Package spvreflect provides Go bindings for SPIRV-Reflect.
*/
package spvreflect
