// MIT License

// WARNING: This file has automatically been generated on Tue, 10 Feb 2026 21:55:43 MSK.
// Code generated by https://git.io/c-for-go. DO NOT EDIT.

/*
Package spvreflect provides Go bindings for SPIRV-Reflect.
*/
package spvreflect
