// MIT License

// WARNING: This file has automatically been generated on Thu, 19 Feb 2026 22:41:19 MSK.
// Code generated by https://git.io/c-for-go. DO NOT EDIT.

package spvreflect

/*
#cgo CFLAGS: -Wno-deprecated-declarations
#include "../../internal/SPIRV-Reflect/spirv_reflect.h"
#include <stdlib.h>
#include "cgo_helpers.h"
*/
import "C"
import "unsafe"

// CreateShaderModule function as declared in SPIRV-Reflect/spirv_reflect.h:656
func CreateShaderModule(Size uint, PCode unsafe.Pointer, PModule *ShaderModule) Result {
	cSize, _ := (C.size_t)(Size), cgoAllocsUnknown
	cPCode, _ := PCode, cgoAllocsUnknown
	cPModule, _ := PModule.PassRef()
	__ret := C.spvReflectCreateShaderModule(cSize, cPCode, cPModule)
	__v := (Result)(__ret)
	return __v
}

// CreateShaderModule2 function as declared in SPIRV-Reflect/spirv_reflect.h:671
func CreateShaderModule2(Flags ModuleFlags, Size uint, PCode unsafe.Pointer, PModule *ShaderModule) Result {
	cFlags, _ := (C.SpvReflectModuleFlags)(Flags), cgoAllocsUnknown
	cSize, _ := (C.size_t)(Size), cgoAllocsUnknown
	cPCode, _ := PCode, cgoAllocsUnknown
	cPModule, _ := PModule.PassRef()
	__ret := C.spvReflectCreateShaderModule2(cFlags, cSize, cPCode, cPModule)
	__v := (Result)(__ret)
	return __v
}

// DestroyShaderModule function as declared in SPIRV-Reflect/spirv_reflect.h:691
func DestroyShaderModule(PModule *ShaderModule) {
	cPModule, _ := PModule.PassRef()
	C.spvReflectDestroyShaderModule(cPModule)
}

// GetCodeSize function as declared in SPIRV-Reflect/spirv_reflect.h:700
func GetCodeSize(PModule *ShaderModule) uint32 {
	cPModule, _ := PModule.PassRef()
	__ret := C.spvReflectGetCodeSize(cPModule)
	__v := (uint32)(__ret)
	return __v
}

// GetCode function as declared in SPIRV-Reflect/spirv_reflect.h:709
func GetCode(PModule *ShaderModule) *uint32 {
	cPModule, _ := PModule.PassRef()
	__ret := C.spvReflectGetCode(cPModule)
	__v := *(**uint32)(unsafe.Pointer(&__ret))
	return __v
}

// GetEntryPoint function as declared in SPIRV-Reflect/spirv_reflect.h:718
func GetEntryPoint(PModule []ShaderModule, EntryPoint string) *EntryPoint {
	cPModule, _ := unpackArgSShaderModule(PModule)
	cEntryPoint, _ := unpackPCharString(EntryPoint)
	__ret := C.spvReflectGetEntryPoint(cPModule, cEntryPoint)
	packSShaderModule(PModule, cPModule)
	__v := NewEntryPointRef(unsafe.Pointer(__ret))
	return __v
}

// EnumerateDescriptorBindings function as declared in SPIRV-Reflect/spirv_reflect.h:741
func EnumerateDescriptorBindings(PModule *ShaderModule, PCount *uint32, PpBindings []*DescriptorBinding) Result {
	cPModule, _ := PModule.PassRef()
	cPCount, _ := (*C.uint32_t)(unsafe.Pointer(PCount)), cgoAllocsUnknown
	cPpBindings, _ := unpackArgSPDescriptorBinding(PpBindings)
	__ret := C.spvReflectEnumerateDescriptorBindings(cPModule, cPCount, cPpBindings)
	packSPDescriptorBinding(PpBindings, cPpBindings)
	__v := (Result)(__ret)
	return __v
}

// EnumerateEntryPointDescriptorBindings function as declared in SPIRV-Reflect/spirv_reflect.h:767
func EnumerateEntryPointDescriptorBindings(PModule *ShaderModule, EntryPoint string, PCount *uint32, PpBindings []*DescriptorBinding) Result {
	cPModule, _ := PModule.PassRef()
	cEntryPoint, _ := unpackPCharString(EntryPoint)
	cPCount, _ := (*C.uint32_t)(unsafe.Pointer(PCount)), cgoAllocsUnknown
	cPpBindings, _ := unpackArgSPDescriptorBinding(PpBindings)
	__ret := C.spvReflectEnumerateEntryPointDescriptorBindings(cPModule, cEntryPoint, cPCount, cPpBindings)
	packSPDescriptorBinding(PpBindings, cPpBindings)
	__v := (Result)(__ret)
	return __v
}

// EnumerateDescriptorSets function as declared in SPIRV-Reflect/spirv_reflect.h:792
func EnumerateDescriptorSets(PModule *ShaderModule, PCount *uint32, PpSets []*DescriptorSet) Result {
	cPModule, _ := PModule.PassRef()
	cPCount, _ := (*C.uint32_t)(unsafe.Pointer(PCount)), cgoAllocsUnknown
	cPpSets, _ := unpackArgSPDescriptorSet(PpSets)
	__ret := C.spvReflectEnumerateDescriptorSets(cPModule, cPCount, cPpSets)
	packSPDescriptorSet(PpSets, cPpSets)
	__v := (Result)(__ret)
	return __v
}

// EnumerateEntryPointDescriptorSets function as declared in SPIRV-Reflect/spirv_reflect.h:818
func EnumerateEntryPointDescriptorSets(PModule *ShaderModule, EntryPoint string, PCount *uint32, PpSets []*DescriptorSet) Result {
	cPModule, _ := PModule.PassRef()
	cEntryPoint, _ := unpackPCharString(EntryPoint)
	cPCount, _ := (*C.uint32_t)(unsafe.Pointer(PCount)), cgoAllocsUnknown
	cPpSets, _ := unpackArgSPDescriptorSet(PpSets)
	__ret := C.spvReflectEnumerateEntryPointDescriptorSets(cPModule, cEntryPoint, cPCount, cPpSets)
	packSPDescriptorSet(PpSets, cPpSets)
	__v := (Result)(__ret)
	return __v
}

// EnumerateInterfaceVariables function as declared in SPIRV-Reflect/spirv_reflect.h:845
func EnumerateInterfaceVariables(PModule *ShaderModule, PCount *uint32, PpVariables []*InterfaceVariable) Result {
	cPModule, _ := PModule.PassRef()
	cPCount, _ := (*C.uint32_t)(unsafe.Pointer(PCount)), cgoAllocsUnknown
	cPpVariables, _ := unpackArgSPInterfaceVariable(PpVariables)
	__ret := C.spvReflectEnumerateInterfaceVariables(cPModule, cPCount, cPpVariables)
	packSPInterfaceVariable(PpVariables, cPpVariables)
	__v := (Result)(__ret)
	return __v
}

// EnumerateEntryPointInterfaceVariables function as declared in SPIRV-Reflect/spirv_reflect.h:870
func EnumerateEntryPointInterfaceVariables(PModule *ShaderModule, EntryPoint string, PCount *uint32, PpVariables []*InterfaceVariable) Result {
	cPModule, _ := PModule.PassRef()
	cEntryPoint, _ := unpackPCharString(EntryPoint)
	cPCount, _ := (*C.uint32_t)(unsafe.Pointer(PCount)), cgoAllocsUnknown
	cPpVariables, _ := unpackArgSPInterfaceVariable(PpVariables)
	__ret := C.spvReflectEnumerateEntryPointInterfaceVariables(cPModule, cEntryPoint, cPCount, cPpVariables)
	packSPInterfaceVariable(PpVariables, cPpVariables)
	__v := (Result)(__ret)
	return __v
}

// EnumerateInputVariables function as declared in SPIRV-Reflect/spirv_reflect.h:897
func EnumerateInputVariables(PModule *ShaderModule, PCount *uint32, PpVariables []*InterfaceVariable) Result {
	cPModule, _ := PModule.PassRef()
	cPCount, _ := (*C.uint32_t)(unsafe.Pointer(PCount)), cgoAllocsUnknown
	cPpVariables, _ := unpackArgSPInterfaceVariable(PpVariables)
	__ret := C.spvReflectEnumerateInputVariables(cPModule, cPCount, cPpVariables)
	packSPInterfaceVariable(PpVariables, cPpVariables)
	__v := (Result)(__ret)
	return __v
}

// EnumerateEntryPointInputVariables function as declared in SPIRV-Reflect/spirv_reflect.h:922
func EnumerateEntryPointInputVariables(PModule *ShaderModule, EntryPoint string, PCount *uint32, PpVariables []*InterfaceVariable) Result {
	cPModule, _ := PModule.PassRef()
	cEntryPoint, _ := unpackPCharString(EntryPoint)
	cPCount, _ := (*C.uint32_t)(unsafe.Pointer(PCount)), cgoAllocsUnknown
	cPpVariables, _ := unpackArgSPInterfaceVariable(PpVariables)
	__ret := C.spvReflectEnumerateEntryPointInputVariables(cPModule, cEntryPoint, cPCount, cPpVariables)
	packSPInterfaceVariable(PpVariables, cPpVariables)
	__v := (Result)(__ret)
	return __v
}

// EnumerateOutputVariables function as declared in SPIRV-Reflect/spirv_reflect.h:949
func EnumerateOutputVariables(PModule *ShaderModule, PCount *uint32, PpVariables []*InterfaceVariable) Result {
	cPModule, _ := PModule.PassRef()
	cPCount, _ := (*C.uint32_t)(unsafe.Pointer(PCount)), cgoAllocsUnknown
	cPpVariables, _ := unpackArgSPInterfaceVariable(PpVariables)
	__ret := C.spvReflectEnumerateOutputVariables(cPModule, cPCount, cPpVariables)
	packSPInterfaceVariable(PpVariables, cPpVariables)
	__v := (Result)(__ret)
	return __v
}

// EnumerateEntryPointOutputVariables function as declared in SPIRV-Reflect/spirv_reflect.h:974
func EnumerateEntryPointOutputVariables(PModule *ShaderModule, EntryPoint string, PCount *uint32, PpVariables []*InterfaceVariable) Result {
	cPModule, _ := PModule.PassRef()
	cEntryPoint, _ := unpackPCharString(EntryPoint)
	cPCount, _ := (*C.uint32_t)(unsafe.Pointer(PCount)), cgoAllocsUnknown
	cPpVariables, _ := unpackArgSPInterfaceVariable(PpVariables)
	__ret := C.spvReflectEnumerateEntryPointOutputVariables(cPModule, cEntryPoint, cPCount, cPpVariables)
	packSPInterfaceVariable(PpVariables, cPpVariables)
	__v := (Result)(__ret)
	return __v
}

// EnumeratePushConstantBlocks function as declared in SPIRV-Reflect/spirv_reflect.h:1002
func EnumeratePushConstantBlocks(PModule *ShaderModule, PCount *uint32, PpBlocks []*BlockVariable) Result {
	cPModule, _ := PModule.PassRef()
	cPCount, _ := (*C.uint32_t)(unsafe.Pointer(PCount)), cgoAllocsUnknown
	cPpBlocks, _ := unpackArgSPBlockVariable(PpBlocks)
	__ret := C.spvReflectEnumeratePushConstantBlocks(cPModule, cPCount, cPpBlocks)
	packSPBlockVariable(PpBlocks, cPpBlocks)
	__v := (Result)(__ret)
	return __v
}

// EnumeratePushConstants function as declared in SPIRV-Reflect/spirv_reflect.h:1008
func EnumeratePushConstants(PModule *ShaderModule, PCount []uint32, PpBlocks [][]BlockVariable) Result {
	cPModule, _ := PModule.PassRef()
	cPCount, _ := (*C.uint32_t)(unsafe.Pointer((*sliceHeader)(unsafe.Pointer(&PCount)).Data)), cgoAllocsUnknown
	cPpBlocks, _ := unpackArgSSBlockVariable(PpBlocks)
	__ret := C.spvReflectEnumeratePushConstants(cPModule, cPCount, cPpBlocks)
	packSSBlockVariable(PpBlocks, cPpBlocks)
	__v := (Result)(__ret)
	return __v
}

// EnumerateEntryPointPushConstantBlocks function as declared in SPIRV-Reflect/spirv_reflect.h:1034
func EnumerateEntryPointPushConstantBlocks(PModule *ShaderModule, EntryPoint string, PCount *uint32, PpBlocks []*BlockVariable) Result {
	cPModule, _ := PModule.PassRef()
	cEntryPoint, _ := unpackPCharString(EntryPoint)
	cPCount, _ := (*C.uint32_t)(unsafe.Pointer(PCount)), cgoAllocsUnknown
	cPpBlocks, _ := unpackArgSPBlockVariable(PpBlocks)
	__ret := C.spvReflectEnumerateEntryPointPushConstantBlocks(cPModule, cEntryPoint, cPCount, cPpBlocks)
	packSPBlockVariable(PpBlocks, cPpBlocks)
	__v := (Result)(__ret)
	return __v
}

// EnumerateSpecializationConstants function as declared in SPIRV-Reflect/spirv_reflect.h:1055
func EnumerateSpecializationConstants(PModule *ShaderModule, PCount *uint32, PpConstants []*SpecializationConstant) Result {
	cPModule, _ := PModule.PassRef()
	cPCount, _ := (*C.uint32_t)(unsafe.Pointer(PCount)), cgoAllocsUnknown
	cPpConstants, _ := unpackArgSPSpecializationConstant(PpConstants)
	__ret := C.spvReflectEnumerateSpecializationConstants(cPModule, cPCount, cPpConstants)
	packSPSpecializationConstant(PpConstants, cPpConstants)
	__v := (Result)(__ret)
	return __v
}

// GetDescriptorBinding function as declared in SPIRV-Reflect/spirv_reflect.h:1083
func GetDescriptorBinding(PModule *ShaderModule, BindingNumber uint32, SetNumber uint32, PResult *Result) *DescriptorBinding {
	cPModule, _ := PModule.PassRef()
	cBindingNumber, _ := (C.uint32_t)(BindingNumber), cgoAllocsUnknown
	cSetNumber, _ := (C.uint32_t)(SetNumber), cgoAllocsUnknown
	cPResult, _ := (*C.SpvReflectResult)(unsafe.Pointer(PResult)), cgoAllocsUnknown
	__ret := C.spvReflectGetDescriptorBinding(cPModule, cBindingNumber, cSetNumber, cPResult)
	__v := NewDescriptorBindingRef(unsafe.Pointer(__ret))
	return __v
}

// GetEntryPointDescriptorBinding function as declared in SPIRV-Reflect/spirv_reflect.h:1115
func GetEntryPointDescriptorBinding(PModule *ShaderModule, EntryPoint string, BindingNumber uint32, SetNumber uint32, PResult *Result) *DescriptorBinding {
	cPModule, _ := PModule.PassRef()
	cEntryPoint, _ := unpackPCharString(EntryPoint)
	cBindingNumber, _ := (C.uint32_t)(BindingNumber), cgoAllocsUnknown
	cSetNumber, _ := (C.uint32_t)(SetNumber), cgoAllocsUnknown
	cPResult, _ := (*C.SpvReflectResult)(unsafe.Pointer(PResult)), cgoAllocsUnknown
	__ret := C.spvReflectGetEntryPointDescriptorBinding(cPModule, cEntryPoint, cBindingNumber, cSetNumber, cPResult)
	__v := NewDescriptorBindingRef(unsafe.Pointer(__ret))
	return __v
}

// GetDescriptorSet function as declared in SPIRV-Reflect/spirv_reflect.h:1140
func GetDescriptorSet(PModule *ShaderModule, SetNumber uint32, PResult *Result) *DescriptorSet {
	cPModule, _ := PModule.PassRef()
	cSetNumber, _ := (C.uint32_t)(SetNumber), cgoAllocsUnknown
	cPResult, _ := (*C.SpvReflectResult)(unsafe.Pointer(PResult)), cgoAllocsUnknown
	__ret := C.spvReflectGetDescriptorSet(cPModule, cSetNumber, cPResult)
	__v := NewDescriptorSetRef(unsafe.Pointer(__ret))
	return __v
}

// GetEntryPointDescriptorSet function as declared in SPIRV-Reflect/spirv_reflect.h:1163
func GetEntryPointDescriptorSet(PModule *ShaderModule, EntryPoint string, SetNumber uint32, PResult *Result) *DescriptorSet {
	cPModule, _ := PModule.PassRef()
	cEntryPoint, _ := unpackPCharString(EntryPoint)
	cSetNumber, _ := (C.uint32_t)(SetNumber), cgoAllocsUnknown
	cPResult, _ := (*C.SpvReflectResult)(unsafe.Pointer(PResult)), cgoAllocsUnknown
	__ret := C.spvReflectGetEntryPointDescriptorSet(cPModule, cEntryPoint, cSetNumber, cPResult)
	__v := NewDescriptorSetRef(unsafe.Pointer(__ret))
	return __v
}

// GetInputVariableByLocation function as declared in SPIRV-Reflect/spirv_reflect.h:1191
func GetInputVariableByLocation(PModule *ShaderModule, Location uint32, PResult *Result) *InterfaceVariable {
	cPModule, _ := PModule.PassRef()
	cLocation, _ := (C.uint32_t)(Location), cgoAllocsUnknown
	cPResult, _ := (*C.SpvReflectResult)(unsafe.Pointer(PResult)), cgoAllocsUnknown
	__ret := C.spvReflectGetInputVariableByLocation(cPModule, cLocation, cPResult)
	__v := NewInterfaceVariableRef(unsafe.Pointer(__ret))
	return __v
}

// GetInputVariable function as declared in SPIRV-Reflect/spirv_reflect.h:1197
func GetInputVariable(PModule *ShaderModule, Location uint32, PResult []Result) *InterfaceVariable {
	cPModule, _ := PModule.PassRef()
	cLocation, _ := (C.uint32_t)(Location), cgoAllocsUnknown
	cPResult, _ := (*C.SpvReflectResult)(unsafe.Pointer((*sliceHeader)(unsafe.Pointer(&PResult)).Data)), cgoAllocsUnknown
	__ret := C.spvReflectGetInputVariable(cPModule, cLocation, cPResult)
	__v := NewInterfaceVariableRef(unsafe.Pointer(__ret))
	return __v
}

// GetEntryPointInputVariableByLocation function as declared in SPIRV-Reflect/spirv_reflect.h:1224
func GetEntryPointInputVariableByLocation(PModule *ShaderModule, EntryPoint string, Location uint32, PResult *Result) *InterfaceVariable {
	cPModule, _ := PModule.PassRef()
	cEntryPoint, _ := unpackPCharString(EntryPoint)
	cLocation, _ := (C.uint32_t)(Location), cgoAllocsUnknown
	cPResult, _ := (*C.SpvReflectResult)(unsafe.Pointer(PResult)), cgoAllocsUnknown
	__ret := C.spvReflectGetEntryPointInputVariableByLocation(cPModule, cEntryPoint, cLocation, cPResult)
	__v := NewInterfaceVariableRef(unsafe.Pointer(__ret))
	return __v
}

// GetInputVariableBySemantic function as declared in SPIRV-Reflect/spirv_reflect.h:1252
func GetInputVariableBySemantic(PModule *ShaderModule, Semantic string, PResult *Result) *InterfaceVariable {
	cPModule, _ := PModule.PassRef()
	cSemantic, _ := unpackPCharString(Semantic)
	cPResult, _ := (*C.SpvReflectResult)(unsafe.Pointer(PResult)), cgoAllocsUnknown
	__ret := C.spvReflectGetInputVariableBySemantic(cPModule, cSemantic, cPResult)
	__v := NewInterfaceVariableRef(unsafe.Pointer(__ret))
	return __v
}

// GetEntryPointInputVariableBySemantic function as declared in SPIRV-Reflect/spirv_reflect.h:1280
func GetEntryPointInputVariableBySemantic(PModule *ShaderModule, EntryPoint string, Semantic string, PResult *Result) *InterfaceVariable {
	cPModule, _ := PModule.PassRef()
	cEntryPoint, _ := unpackPCharString(EntryPoint)
	cSemantic, _ := unpackPCharString(Semantic)
	cPResult, _ := (*C.SpvReflectResult)(unsafe.Pointer(PResult)), cgoAllocsUnknown
	__ret := C.spvReflectGetEntryPointInputVariableBySemantic(cPModule, cEntryPoint, cSemantic, cPResult)
	__v := NewInterfaceVariableRef(unsafe.Pointer(__ret))
	return __v
}

// GetOutputVariableByLocation function as declared in SPIRV-Reflect/spirv_reflect.h:1307
func GetOutputVariableByLocation(PModule *ShaderModule, Location uint32, PResult *Result) *InterfaceVariable {
	cPModule, _ := PModule.PassRef()
	cLocation, _ := (C.uint32_t)(Location), cgoAllocsUnknown
	cPResult, _ := (*C.SpvReflectResult)(unsafe.Pointer(PResult)), cgoAllocsUnknown
	__ret := C.spvReflectGetOutputVariableByLocation(cPModule, cLocation, cPResult)
	__v := NewInterfaceVariableRef(unsafe.Pointer(__ret))
	return __v
}

// GetOutputVariable function as declared in SPIRV-Reflect/spirv_reflect.h:1313
func GetOutputVariable(PModule *ShaderModule, Location uint32, PResult []Result) *InterfaceVariable {
	cPModule, _ := PModule.PassRef()
	cLocation, _ := (C.uint32_t)(Location), cgoAllocsUnknown
	cPResult, _ := (*C.SpvReflectResult)(unsafe.Pointer((*sliceHeader)(unsafe.Pointer(&PResult)).Data)), cgoAllocsUnknown
	__ret := C.spvReflectGetOutputVariable(cPModule, cLocation, cPResult)
	__v := NewInterfaceVariableRef(unsafe.Pointer(__ret))
	return __v
}

// GetEntryPointOutputVariableByLocation function as declared in SPIRV-Reflect/spirv_reflect.h:1340
func GetEntryPointOutputVariableByLocation(PModule *ShaderModule, EntryPoint string, Location uint32, PResult *Result) *InterfaceVariable {
	cPModule, _ := PModule.PassRef()
	cEntryPoint, _ := unpackPCharString(EntryPoint)
	cLocation, _ := (C.uint32_t)(Location), cgoAllocsUnknown
	cPResult, _ := (*C.SpvReflectResult)(unsafe.Pointer(PResult)), cgoAllocsUnknown
	__ret := C.spvReflectGetEntryPointOutputVariableByLocation(cPModule, cEntryPoint, cLocation, cPResult)
	__v := NewInterfaceVariableRef(unsafe.Pointer(__ret))
	return __v
}

// GetOutputVariableBySemantic function as declared in SPIRV-Reflect/spirv_reflect.h:1368
func GetOutputVariableBySemantic(PModule *ShaderModule, Semantic string, PResult *Result) *InterfaceVariable {
	cPModule, _ := PModule.PassRef()
	cSemantic, _ := unpackPCharString(Semantic)
	cPResult, _ := (*C.SpvReflectResult)(unsafe.Pointer(PResult)), cgoAllocsUnknown
	__ret := C.spvReflectGetOutputVariableBySemantic(cPModule, cSemantic, cPResult)
	__v := NewInterfaceVariableRef(unsafe.Pointer(__ret))
	return __v
}

// GetEntryPointOutputVariableBySemantic function as declared in SPIRV-Reflect/spirv_reflect.h:1396
func GetEntryPointOutputVariableBySemantic(PModule *ShaderModule, EntryPoint string, Semantic string, PResult *Result) *InterfaceVariable {
	cPModule, _ := PModule.PassRef()
	cEntryPoint, _ := unpackPCharString(EntryPoint)
	cSemantic, _ := unpackPCharString(Semantic)
	cPResult, _ := (*C.SpvReflectResult)(unsafe.Pointer(PResult)), cgoAllocsUnknown
	__ret := C.spvReflectGetEntryPointOutputVariableBySemantic(cPModule, cEntryPoint, cSemantic, cPResult)
	__v := NewInterfaceVariableRef(unsafe.Pointer(__ret))
	return __v
}

// GetPushConstantBlock function as declared in SPIRV-Reflect/spirv_reflect.h:1420
func GetPushConstantBlock(PModule *ShaderModule, Index uint32, PResult *Result) *BlockVariable {
	cPModule, _ := PModule.PassRef()
	cIndex, _ := (C.uint32_t)(Index), cgoAllocsUnknown
	cPResult, _ := (*C.SpvReflectResult)(unsafe.Pointer(PResult)), cgoAllocsUnknown
	__ret := C.spvReflectGetPushConstantBlock(cPModule, cIndex, cPResult)
	__v := NewBlockVariableRef(unsafe.Pointer(__ret))
	return __v
}

// GetPushConstant function as declared in SPIRV-Reflect/spirv_reflect.h:1426
func GetPushConstant(PModule *ShaderModule, Index uint32, PResult []Result) *BlockVariable {
	cPModule, _ := PModule.PassRef()
	cIndex, _ := (C.uint32_t)(Index), cgoAllocsUnknown
	cPResult, _ := (*C.SpvReflectResult)(unsafe.Pointer((*sliceHeader)(unsafe.Pointer(&PResult)).Data)), cgoAllocsUnknown
	__ret := C.spvReflectGetPushConstant(cPModule, cIndex, cPResult)
	__v := NewBlockVariableRef(unsafe.Pointer(__ret))
	return __v
}

// GetEntryPointPushConstantBlock function as declared in SPIRV-Reflect/spirv_reflect.h:1451
func GetEntryPointPushConstantBlock(PModule *ShaderModule, EntryPoint string, PResult *Result) *BlockVariable {
	cPModule, _ := PModule.PassRef()
	cEntryPoint, _ := unpackPCharString(EntryPoint)
	cPResult, _ := (*C.SpvReflectResult)(unsafe.Pointer(PResult)), cgoAllocsUnknown
	__ret := C.spvReflectGetEntryPointPushConstantBlock(cPModule, cEntryPoint, cPResult)
	__v := NewBlockVariableRef(unsafe.Pointer(__ret))
	return __v
}

// ChangeDescriptorBindingNumbers function as declared in SPIRV-Reflect/spirv_reflect.h:1481
func ChangeDescriptorBindingNumbers(PModule *ShaderModule, PBinding *DescriptorBinding, NewBindingNumber uint32, NewSetNumber uint32) Result {
	cPModule, _ := PModule.PassRef()
	cPBinding, _ := PBinding.PassRef()
	cNewBindingNumber, _ := (C.uint32_t)(NewBindingNumber), cgoAllocsUnknown
	cNewSetNumber, _ := (C.uint32_t)(NewSetNumber), cgoAllocsUnknown
	__ret := C.spvReflectChangeDescriptorBindingNumbers(cPModule, cPBinding, cNewBindingNumber, cNewSetNumber)
	__v := (Result)(__ret)
	return __v
}

// ChangeDescriptorBindingNumber function as declared in SPIRV-Reflect/spirv_reflect.h:1488
func ChangeDescriptorBindingNumber(PModule *ShaderModule, PDescriptorBinding []DescriptorBinding, NewBindingNumber uint32, OptionalNewSetNumber uint32) Result {
	cPModule, _ := PModule.PassRef()
	cPDescriptorBinding, _ := unpackArgSDescriptorBinding(PDescriptorBinding)
	cNewBindingNumber, _ := (C.uint32_t)(NewBindingNumber), cgoAllocsUnknown
	cOptionalNewSetNumber, _ := (C.uint32_t)(OptionalNewSetNumber), cgoAllocsUnknown
	__ret := C.spvReflectChangeDescriptorBindingNumber(cPModule, cPDescriptorBinding, cNewBindingNumber, cOptionalNewSetNumber)
	packSDescriptorBinding(PDescriptorBinding, cPDescriptorBinding)
	__v := (Result)(__ret)
	return __v
}

// ChangeDescriptorSetNumber function as declared in SPIRV-Reflect/spirv_reflect.h:1517
func ChangeDescriptorSetNumber(PModule *ShaderModule, PSet *DescriptorSet, NewSetNumber uint32) Result {
	cPModule, _ := PModule.PassRef()
	cPSet, _ := PSet.PassRef()
	cNewSetNumber, _ := (C.uint32_t)(NewSetNumber), cgoAllocsUnknown
	__ret := C.spvReflectChangeDescriptorSetNumber(cPModule, cPSet, cNewSetNumber)
	__v := (Result)(__ret)
	return __v
}

// ChangeInputVariableLocation function as declared in SPIRV-Reflect/spirv_reflect.h:1540
func ChangeInputVariableLocation(PModule *ShaderModule, PInputVariable *InterfaceVariable, NewLocation uint32) Result {
	cPModule, _ := PModule.PassRef()
	cPInputVariable, _ := PInputVariable.PassRef()
	cNewLocation, _ := (C.uint32_t)(NewLocation), cgoAllocsUnknown
	__ret := C.spvReflectChangeInputVariableLocation(cPModule, cPInputVariable, cNewLocation)
	__v := (Result)(__ret)
	return __v
}

// ChangeOutputVariableLocation function as declared in SPIRV-Reflect/spirv_reflect.h:1564
func ChangeOutputVariableLocation(PModule *ShaderModule, POutputVariable *InterfaceVariable, NewLocation uint32) Result {
	cPModule, _ := PModule.PassRef()
	cPOutputVariable, _ := POutputVariable.PassRef()
	cNewLocation, _ := (C.uint32_t)(NewLocation), cgoAllocsUnknown
	__ret := C.spvReflectChangeOutputVariableLocation(cPModule, cPOutputVariable, cNewLocation)
	__v := (Result)(__ret)
	return __v
}

// SourceLanguageName function as declared in SPIRV-Reflect/spirv_reflect.h:1577
func SourceLanguageName(SourceLang SourceLanguage) string {
	cSourceLang, _ := (C.SpvSourceLanguage)(SourceLang), cgoAllocsUnknown
	__ret := C.spvReflectSourceLanguage(cSourceLang)
	__v := packPCharString(__ret)
	return __v
}

// BlockVariableTypeName function as declared in SPIRV-Reflect/spirv_reflect.h:1585
func BlockVariableTypeName(PVar []BlockVariable) string {
	cPVar, _ := unpackArgSBlockVariable(PVar)
	__ret := C.spvReflectBlockVariableTypeName(cPVar)
	packSBlockVariable(PVar, cPVar)
	__v := packPCharString(__ret)
	return __v
}
