// MIT License

// WARNING: This file has automatically been generated on Tue, 10 Feb 2026 21:55:43 MSK.
// Code generated by https://git.io/c-for-go. DO NOT EDIT.

package spvreflect

/*
#cgo CFLAGS: -Wno-deprecated-declarations
#include "../../internal/SPIRV-Reflect/spirv_reflect.h"
#include <stdlib.h>
#include "cgo_helpers.h"
*/
import "C"
import "unsafe"

// ModuleFlags type as declared in SPIRV-Reflect/spirv_reflect.h:103
type ModuleFlags uint32

// TypeFlags type as declared in SPIRV-Reflect/spirv_reflect.h:127
type TypeFlags uint32

// DecorationFlags type as declared in SPIRV-Reflect/spirv_reflect.h:161
type DecorationFlags uint32

// VariableFlags type as declared in SPIRV-Reflect/spirv_reflect.h:271
type VariableFlags uint32

// NumericTraits as declared in SPIRV-Reflect/spirv_reflect.h:356
type NumericTraits struct {
	ref3d621819    *C.SpvReflectNumericTraits
	allocs3d621819 interface{}
}

// ImageTraits as declared in SPIRV-Reflect/spirv_reflect.h:365
type ImageTraits struct {
	Dim            Dim
	Depth          uint32
	Arrayed        uint32
	Ms             uint32
	Sampled        uint32
	ImageFormat    ImageFormat
	refdb040274    *C.SpvReflectImageTraits
	allocsdb040274 interface{}
}

// ArrayTraits as declared in SPIRV-Reflect/spirv_reflect.h:381
type ArrayTraits struct {
	DimsCount         uint32
	Dims              [32]uint32
	SpecConstantOpIds [32]uint32
	Stride            uint32
	ref443eb8dd       *C.SpvReflectArrayTraits
	allocs443eb8dd    interface{}
}

// BindingArrayTraits as declared in SPIRV-Reflect/spirv_reflect.h:386
type BindingArrayTraits struct {
	DimsCount      uint32
	Dims           [32]uint32
	ref611ee120    *C.SpvReflectBindingArrayTraits
	allocs611ee120 interface{}
}

// TypeDescription as declared in SPIRV-Reflect/spirv_reflect.h:421
type TypeDescription struct {
	Id                    uint32
	Op                    Op
	TypeName              string
	StructMemberName      string
	StorageClass          int32
	TypeFlags             TypeFlags
	DecorationFlags       DecorationFlags
	StructTypeDescription []TypeDescription
	Copied                uint32
	MemberCount           uint32
	Members               []TypeDescription
	ref1250b8c8           *C.SpvReflectTypeDescription
	allocs1250b8c8        interface{}
}

// InterfaceVariable as declared in SPIRV-Reflect/spirv_reflect.h:455
type InterfaceVariable struct {
	SpirvId         uint32
	Name            string
	Location        uint32
	Component       uint32
	StorageClass    StorageClass
	Semantic        string
	DecorationFlags DecorationFlags
	BuiltIn         int32
	Numeric         NumericTraits
	Array           ArrayTraits
	MemberCount     uint32
	Members         []InterfaceVariable
	Format          Format
	TypeDescription []TypeDescription
	refab7c479d     *C.SpvReflectInterfaceVariable
	allocsab7c479d  interface{}
}

// BlockVariable as declared in SPIRV-Reflect/spirv_reflect.h:482
type BlockVariable struct {
	SpirvId         uint32
	Name            string
	Offset          uint32
	AbsoluteOffset  uint32
	Size            uint32
	PaddedSize      uint32
	DecorationFlags DecorationFlags
	Numeric         NumericTraits
	Array           ArrayTraits
	Flags           VariableFlags
	MemberCount     uint32
	Members         []BlockVariable
	TypeDescription []TypeDescription
	ref1455998a     *C.SpvReflectBlockVariable
	allocs1455998a  interface{}
}

// DescriptorBinding as declared in SPIRV-Reflect/spirv_reflect.h:515
type DescriptorBinding struct {
	SpirvId                      uint32
	Name                         string
	Binding                      uint32
	InputAttachmentIndex         uint32
	Set                          uint32
	DescriptorType               DescriptorType
	ResourceType                 ResourceType
	Image                        ImageTraits
	Block                        BlockVariable
	Array                        BindingArrayTraits
	Count                        uint32
	Accessed                     uint32
	UavCounterId                 uint32
	UavCounterBinding            []DescriptorBinding
	ByteAddressBufferOffsetCount uint32
	ByteAddressBufferOffsets     []uint32
	TypeDescription              []TypeDescription
	DecorationFlags              DecorationFlags
	UserType                     UserType
	ref72816273                  *C.SpvReflectDescriptorBinding
	allocs72816273               interface{}
}

// DescriptorSet as declared in SPIRV-Reflect/spirv_reflect.h:524
type DescriptorSet struct {
	Set            uint32
	BindingCount   uint32
	Bindings       [][]DescriptorBinding
	ref95bcf29b    *C.SpvReflectDescriptorSet
	allocs95bcf29b interface{}
}

// EntryPoint as declared in SPIRV-Reflect/spirv_reflect.h:565
type EntryPoint struct {
	Name                   string
	Id                     uint32
	SpirvExecutionModel    ExecutionModel
	ShaderStage            ShaderStageFlagBits
	InputVariableCount     uint32
	InputVariables         [][]InterfaceVariable
	OutputVariableCount    uint32
	OutputVariables        [][]InterfaceVariable
	InterfaceVariableCount uint32
	InterfaceVariables     []InterfaceVariable
	DescriptorSetCount     uint32
	DescriptorSets         []DescriptorSet
	UsedUniformCount       uint32
	UsedUniforms           []uint32
	UsedPushConstantCount  uint32
	UsedPushConstants      []uint32
	ExecutionModeCount     uint32
	ExecutionModes         []ExecutionMode
	Invocations            uint32
	OutputVertices         uint32
	reff018ae0f            *C.SpvReflectEntryPoint
	allocsf018ae0f         interface{}
}

// CapabilityInfo as declared in SPIRV-Reflect/spirv_reflect.h:573
type CapabilityInfo struct {
	Value          Capability
	WordOffset     uint32
	refe9ca9817    *C.SpvReflectCapability
	allocse9ca9817 interface{}
}

// SpecializationConstant as declared in SPIRV-Reflect/spirv_reflect.h:598
type SpecializationConstant struct {
	SpirvId          uint32
	ConstantId       uint32
	Name             string
	TypeDescription  []TypeDescription
	DefaultValueSize uint32
	DefaultValue     unsafe.Pointer
	ref8a46bef0      *C.SpvReflectSpecializationConstant
	allocs8a46bef0   interface{}
}

// ShaderModule as declared in SPIRV-Reflect/spirv_reflect.h:642
type ShaderModule struct {
	Generator              Generator
	EntryPointName         string
	EntryPointId           uint32
	EntryPointCount        uint32
	EntryPoints            []EntryPoint
	SourceLanguage         SourceLanguage
	SourceLanguageVersion  uint32
	SourceFile             string
	SourceSource           string
	CapabilityCount        uint32
	Capabilities           []CapabilityInfo
	SpirvExecutionModel    ExecutionModel
	ShaderStage            ShaderStageFlagBits
	DescriptorBindingCount uint32
	DescriptorBindings     []DescriptorBinding
	DescriptorSetCount     uint32
	DescriptorSets         [64]DescriptorSet
	InputVariableCount     uint32
	InputVariables         [][]InterfaceVariable
	OutputVariableCount    uint32
	OutputVariables        [][]InterfaceVariable
	InterfaceVariableCount uint32
	InterfaceVariables     []InterfaceVariable
	PushConstantBlockCount uint32
	PushConstantBlocks     []BlockVariable
	SpecConstantCount      uint32
	SpecConstants          []SpecializationConstant
	refce1fe5ac            *C.SpvReflectShaderModule
	allocsce1fe5ac         interface{}
}

// Id type as declared in unified1/spirv.h:40
type Id uint32
